name = "babynamescout"
compatibility_date = "2024-09-23"
pages_build_output_dir = "out"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Preview environment
[env.preview]
name = "babynamescout-preview"
